version: '3.7'
services:
  backend:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
      args:
        INSTALL_DEV: 'True'
  frontend:
    build:
      context: ./frontend
  docs:
    build:
      context: ./docs
